SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('chat/', include('chat.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views
from django.contrib.auth.models import User

urlpatterns = [
    path('', views.index_view, name = 'index'),
    path('<str:user_name>/', views.room_view, name = 'room')
]

core/urls.py
from django.urls import path
from . import views


app_name = 'core'

urlpatterns=[
    path('', views.RegistrationView, name='register' ),
    path('login/', views.LoginView, name='login'),
    path('login/success/', views.successLogin, name='login-success'),
    path('profile/<str:user_name>/', views.displayUserProfile, name='user_profile_page'),
    path('profile/<str:user_name>/edit/',views.editProfile,name = "edit_profile"),
    path('profile/<str:user_name>/logout', views.userLogout , name="logout"),
    path('profile/<str:user_name>/follow/', views.userFollow, name="user_Follow"),
    path('profile/<str:user_name>/create_post',views.create_post,name="create_post"),
    path('profile/<str:user_name>/unfollow/', views.userUnfollow, name="user_Unfollow"),
    path('profile/<str:user_name>/<int:post_id>/create_comment',views.createComment , name = "create_comment"),
    path('profile/<str:user_name>/feed',views.displayFeed, name = "user_feed"),
    path('profile/<str:user_name>/<int:post_id>/like',views.postLike, name="post_like"),
    path('profile/<str:user_name>/followers',views.show_followers,name="see_followers")
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=300)
    city = models.CharField(max_length=20)
    country = models.CharField(max_length=20)

    profile_pic = models.ImageField(upload_to='profile_pics/', default='profile_pics/None/default.jpg')
    cover_pic = models.ImageField(upload_to='cover_pics/', default='cover_pics/None/cover_default.jpg')

    def __str__(self):
        return self.user.username


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(null=True)
    likes = models.IntegerField(default=0)
    published_date = models.DateTimeField(auto_now_add=True)
    likes_user=models.ManyToManyField(User,related_name="liked")

    def __str__(self):
        return str(self.content)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(null = True)
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post.author + '-' + self.author

class Follow(models.Model):
    to_follow = models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    follower = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.to_follow) + '<-' + str(self.follower)

core/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields=['username', 'email', 'password']

core/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.views.generic import View
from . import forms
from .models import *



# Create your views here.


def LoginView(request):
    if request.method == "GET":
        return render(request, 'core/login.html')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('core:login-success')
        else:
            error_message = "Wrong Password or Username"
            return render(request,'core/login.html',{'error_message': error_message})


def successLogin(request):
    return redirect('core:user_feed', user_name = request.user.username)

def RegistrationView(request):

    if request.method == "GET":
        return render(request, 'core/register.html')

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        emailid = request.POST['emailid']


        if not (User.objects.filter(username=username).exists()):
            user = User.objects.create_user(username, emailid, password)
            Follow.objects.create(to_follow=user, follower=user)
            UserProfile.objects.create(user=user)


        else:

            error_message = "The user already exists!"
            return render(request, 'core/register.html', {'error_message': error_message})


        return redirect('core:login')


def displayUserProfile(request,user_name):
    user = User.objects.get(username=user_name)
    current_user = User.objects.get(username=request.user.username)
    if Follow.objects.filter(to_follow=user, follower=current_user).exists():
        follows = "Unfollow"
    else:
        follows = "Follow"
    return render (request, 'core/profile.html', {'user': user, 'follow': follows})



def editProfile(request, user_name):
    user = User.objects.get(username=user_name)
    if request.method=='POST':
       user.userprofile.bio = request.POST['bio']
       if request.POST['password']:
           user.set_password(request.POST['password'])

       user.userprofile.city = request.POST['city']
       user.userprofile.country = request.POST['country']
       if request.FILES['profilepic']:
           user.userprofile.profile_pic = request.FILES['profilepic']
       if request.FILES['coverpic']:
           user.userprofile.cover_pic = request.FILES['coverpic']
       user.save()
       user.userprofile.save()
       return redirect('core:user_profile_page', user_name = user.username)


def userLogout(request, user_name):
    logout(request)
    return redirect('core:login')


def userFollow(request, user_name):
    user_to_follow = User.objects.get(username=user_name)
    current_user = User.objects.get(username=request.user.username)
    if not Follow.objects.filter(to_follow=user_to_follow, follower=current_user):
        Follow.objects.create(to_follow=user_to_follow, follower=current_user)
    #current_user.userprofile.follows.add(user_to_follow.userprofile)
    #current_user.userprofile.save()
    return redirect('core:user_profile_page', user_name=user_to_follow.username)

def create_post(request,user_name):
    if request.method == "POST":
        newpost = Post()
        newpost.author = User.objects.get(username=user_name)
        newpost.content = request.POST["content"]
        newpost.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        #return redirect('core:user_profile_page',user_name=user_name)

def userUnfollow(request, user_name):
    user_to_unfollow = User.objects.get(username=user_name)
    current_user = User.objects.get(username=request.user.username)
    Follow.objects.filter(to_follow=user_to_unfollow, follower=current_user).delete()
    #current_user.userprofile.follows.remove(user_to_unfollow.userprofile)
    return redirect('core:user_profile_page', user_name = user_to_unfollow.username)

def createComment(request, user_name, post_id):
    if request.method == "POST":
        post_for_comment = Post.objects.get(id = post_id)
        Comment.objects.create(author=request.user, post=post_for_comment, content= request.POST['comment'])
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        #return redirect('core:user_profile_page', user_name = user_name)

def displayFeed(request, user_name):
    current_user = User.objects.get(username=request.user.username)
    postsum = Post.objects.filter(author__in=Follow.objects.filter(follower=current_user).values('to_follow')).order_by('published_date')

    return render(request, 'core/feed.html', {'user' : current_user, 'posts' : postsum})


def postLike(request, user_name, post_id):

        post_for_comment = Post.objects.get(id = post_id)
        user_like = User.objects.get(username=user_name)
        if user_like not in post_for_comment.likes_user.all():
            post_for_comment.likes += 1
            post_for_comment.likes_user.add(user_like)
            post_for_comment.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        #return redirect('core:user_profile_page', user_name = user_name)

def show_followers(request,user_name):
    follow_list = Follow.objects.filter(to_follow__username=user_name)
    return render(request,"core/followers.html",{"list": follow_list})

core/templates/core/login.html
{% load static %}
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="./favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
    <!-- Generated: 2018-04-16 09:29:05 +0200 -->
    <title>Login - tabler.github.io - a responsive, flat and full featured admin template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <script src=" {%  static 'js/require.min.js' %}"></script>
    <script>
      requirejs.config({
          baseUrl: '.'
      });
    </script>
    <!-- Dashboard Core -->
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet" />
    <script src=" {% static 'js/dashboard.js' %}"></script>
    <!-- c3.js Charts Plugin -->
    <link href="{% static 'plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <script src="{% static 'plugins/charts-c3/plugin.js' %}"></script>
    <!-- Google Maps Plugin -->
    <link href="{% static 'plugins/maps-google/plugin.css' %}" rel="stylesheet" />
    <script src="{% static 'plugins/maps-google/plugin.js' %}"></script>
    <!-- Input Mask Plugin -->
    <script src="{% static '/plugins/input-mask/plugin.js' %}"></script>
  </head>
  <body class="">
    <div class="page">
      <div class="page-single">
        <div class="container">
          <div class="row">
            <div class="col col-login mx-auto">
              <div class="text-center mb-6">
                <!-- <img src="./assets/brand/tabler.svg" class="h-6" alt="">-->
              </div>

              <form class="card" action="" method="post">
                  {% csrf_token %}
                <div class="card-body p-6">
                    {% if error_message %}
                  <p style="color:red">{{ error_message }}</p>
                  {% endif %}
                  <div class="card-title">Login to your account</div>
                  <div class="form-group">
                    <label class="form-label">Username</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter username" name="username">
                  </div>
                  <div class="form-group">
                    <label class="form-label">
                      Password
                      <a href="./forgot-password.html" class="float-right small">I forgot password</a>
                    </label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
                  </div>

                  <div class="form-footer">
                    <button type="submit" class="btn btn-primary btn-block">Sign in</button>
                  </div>
                </div>
              </form>
              <div class="text-center text-muted">
                Don't have account yet? <a href="{% url 'core:register' %}">Sign up</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

core/templates/core/register.html
{% load static %}
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="./favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
    <!-- Generated: 2018-04-16 09:29:05 +0200 -->
    <title>Register - tabler.github.io - a responsive, flat and full featured admin template</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <script src="{% static "js/require.min.js"%}"></script>
    <script>
      requirejs.config({
          baseUrl: '.'
      });
    </script>
    <!-- Dashboard Core -->
    <link href="{% static "css/dashboard.css"%}" rel="stylesheet" />
    <script src="{%  static "js/dashboard.js"%}"></script>
    <!-- c3.js Charts Plugin -->
    <link href="{%  static "plugins/charts-c3/plugin.css"%}" rel="stylesheet" />
    <script src="{%  static "plugins/charts-c3/plugin.js"%}"></script>
    <!-- Google Maps Plugin -->
    <link href="{%  static "plugins/maps-google/plugin.css" %}" rel="stylesheet" />
    <script src="{%  static "plugins/maps-google/plugin.js" %}"></script>
    <!-- Input Mask Plugin -->
    <script src="{%  static "plugins/input-mask/plugin.js" %}"></script>
  </head>
  <body class="">
    <div class="page">
      <div class="page-single">
        <div class="container">
          <div class="row">
            <div class="col col-login mx-auto">
              <div class="text-center mb-6">
                <!--<img src="./assets/brand/tabler.svg" class="h-6" alt=""> -->
                  {% if error_message %}
                  <p style="color:red">{{ error_message }}</p>
                  {% endif %}
              <form class="card" action="" method="post">
                  {% csrf_token %}
                <div class="card-body p-6">
                  <div class="card-title">Create new account</div>
                  <div class="form-group">
                    <label class="form-label">Username</label>
                    <input type="text" class="form-control" placeholder="Enter username" name="username">
                  </div>
                  <div class="form-group">
                    <label class="form-label">Email address</label>
                    <input type="email" class="form-control" placeholder="Enter email" name="emailid">
                  </div>
                  <div class="form-group">
                    <label class="form-label">Password</label>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                  </div>

                  <div class="form-footer">
                    <button type="submit" class="btn btn-primary btn-block">Create new account</button>
                  </div>
                </div>
              </form>
              <div class="text-center text-muted">
                Already have account? <a href="{% url 'core:login' %}">Sign in</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>